### ISSUE TITLE
IntLogicalType, isSigned=false, bitWidth=64 not supported

### ISSUE THREAD

**Issue by corani** [devinrsmith/deephaven-parquet-viewer#77]
I'm encountering the following error while trying to load some parquet files (using docker latest):

```log
Initiating shutdown due to: Uncaught exception in thread main
java.lang.RuntimeException: Error encountered at line 3: parquet_table = ParquetTools.readTable('/file.parquet')
        at io.deephaven.engine.util.GroovyDeephavenSession.maybeRewriteStackTrace(GroovyDeephavenSession.java:386)
        at io.deephaven.engine.util.GroovyDeephavenSession.wrapAndRewriteStackTrace(GroovyDeephavenSession.java:364)
        at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:357)
        at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:165)
        at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:196)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:207)
        at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:195)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:165)
        at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:236)
        at io.deephaven.server.appmode.ApplicationFactory.evaluateScripts(ApplicationFactory.java:98)
        at io.deephaven.server.appmode.ApplicationFactory.lambda$visit$0(ApplicationFactory.java:66)
        at io.deephaven.appmode.ApplicationContext.runUnderContext(ApplicationContext.java:36)
        at io.deephaven.server.appmode.ApplicationFactory.visit(ApplicationFactory.java:66)
        at io.deephaven.appmode.ScriptApplication.walk(ScriptApplication.java:49)
        at io.deephaven.server.appmode.ApplicationFactory.create(ApplicationFactory.java:27)
        at io.deephaven.server.appmode.ApplicationInjector.loadApplication(ApplicationInjector.java:90)
        at io.deephaven.server.appmode.ApplicationInjector.run(ApplicationInjector.java:78)
        at io.deephaven.server.runner.DeephavenApiServer.run(DeephavenApiServer.java:208)
        at io.deephaven.server.jetty.JettyMain.main(JettyMain.java:24)
Caused by: io.deephaven.UncheckedDeephavenException: Unable to read column [__sequence_number]: IntLogicalType, isSigned=false, bitWidth=64 not supported
        at io.deephaven.parquet.table.ParquetSchemaReader.lambda$readParquetSchema$2(ParquetSchemaReader.java:264)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.deephaven.parquet.table.ParquetSchemaReader.readParquetSchema(ParquetSchemaReader.java:258)
        at io.deephaven.parquet.table.ParquetSchemaReader.convertSchema(ParquetSchemaReader.java:289)
        at io.deephaven.parquet.table.ParquetTools.infer(ParquetTools.java:906)
        at io.deephaven.parquet.table.ParquetTools.readSingleFileTable(ParquetTools.java:1047)
        at io.deephaven.parquet.table.ParquetTools.readTable(ParquetTools.java:146)
        at io.deephaven.parquet.table.ParquetTools.readTable(ParquetTools.java:105)
        at io.deephaven.parquet.table.ParquetTools$readTable.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at io.deephaven.dynamic._opt_deephaven_config_app_d_parquet_viewer_groovy_6.run(_opt_deephaven_config_app_d_parquet_viewer_groovy_6.groovy:4)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
        at io.deephaven.engine.util.GroovyDeephavenSession.lambda$evaluate$0(GroovyDeephavenSession.java:352)
        at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
        at io.deephaven.engine.util.GroovyDeephavenSession.evaluate(GroovyDeephavenSession.java:352)
        ... 16 more

```

**Comment by devinrsmith** [comment]
This is ultimately an issue for https://github.com/deephaven/deephaven-core; there are certain types of parquet values that can't currently be mapped (Java has no native uint64 type... but there may be workarounds). In this case, it looks like it's an _unsigned_ 64-bit integer. Once it gets fixed on deephaven-core side, it should automatically get fixed here. Would you be able to post an issue there @corani ?
